export const MOCK_COURSES = [
  {
      "id": 665,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "Priv Img",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://school.boukii.com/assets/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 4,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-17",
      "date_start_format": "17/10/2023",
      "date_end": "2023-10-26",
      "date_end_format": "26/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:12:21"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://school.boukii.com/assets/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://school.boukii.com/assets/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://school.boukii.com/assets/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://school.boukii.com/assets/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://school.boukii.com/assets/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://school.boukii.com/assets/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://school.boukii.com/assets/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://school.boukii.com/assets/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://school.boukii.com/assets/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  }
];
