export const MOCK_COURSES = [
  {
      "id": 665,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "Priv Img",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://api.boukii.com/storage/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 4,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-17",
      "date_start_format": "17/10/2023",
      "date_end": "2023-10-26",
      "date_end_format": "26/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:12:21"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://api.boukii.com/storage/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://api.boukii.com/storage/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://api.boukii.com/storage/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://api.boukii.com/storage/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://api.boukii.com/storage/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://api.boukii.com/storage/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://api.boukii.com/storage/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://api.boukii.com/storage/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  },
  {
      "id": 666,
      "definido": 0,
      "libre": 1,
      "course_supertype_id": 2,
      "course_type_id": 2,
      "sport_id": 1,
      "name": "priv img test",
      "subtitle": "Private Ski",
      "short_description": "<p>123</p>",
      "description": "<p>123</p>",
      "icon": "https://api.boukii.com/storage/icons/prive_ski2x.png",
      "price": 160,
      "currency": "CHF",
      "max_participants": 3,
      "hour_min": null,
      "hour_max": null,
      "day_start_res": "monday",
      "day_end_res": "sunday",
      "date_start": "2023-10-24",
      "date_start_format": "24/10/2023",
      "date_end": "2023-10-31",
      "date_end_format": "31/10/2023",
      "date_start_res": "2023-10-17",
      "date_start_res_format": "17/10/2023",
      "date_end_res": "2023-10-17",
      "date_end_res_format": "17/10/2023",
      "duration": "01:00",
      "duration_hours": "1",
      "duration_minutes": "",
      "duration_seconds": "",
      "duration_flexible": 0,
      "school_id": 1,
      "station": {
          "id": 1,
          "name": "Les Paccots"
      },
      "price_ranges": [],
      "global_course": null,
      "confirm_attendance": 0,
      "online": 1,
      "active": 1,
      "group_id": null,
      "created_at": "2023-10-10 11:19:40"
  }
];


export const MOCK_COLECTIVE_COURSES = {
  "active": 1,
  "checked": 1,
  "confirm_attendance": 0,
  "course_supertype_id": 1,
  "course_type_id": 1,
  "created_at": "2023-10-10 11:07:25",
  "currency": "CHF",
  "date_end": "2023-10-24",
  "date_end_format": "24/10/2023",
  "date_end_res": "2023-10-17",
  "date_end_res_format": "17/10/2023",
  "date_start": "2023-10-24",
  "date_start_format": "24/10/2023",
  "date_start_res": "2023-10-17",
  "date_start_res_format": "17/10/2023",
  "dates": [
    {
        "id": 1433,
        "date": "2023-10-24",
        "date_format": "24/10/2023",
        "hour": "08:00",
        "hour_end": "09:00",
        "created_at": "2023-10-10T09:07:26.000000Z",
        "updated_at": "2023-10-10T09:07:26.000000Z"
    }
],
  "day_end_res": null,
  "day_start_res": null,
  "definido": 1,
  "description": "<p>123</p>",
  "duration": "01:00",
  "duration_flexible": 0,
  "duration_hours": "1",
  "duration_minutes": "",
  "duration_seconds": "",
  "global_course": {
      "id": 48,
      "date_start_global": "2023-10-24",
      "date_end_global": "2023-10-26",
      "name_global": "Fix Img test",
      "short_description_global": "<p>123</p>"
  },
  "group_courses": [{}],
  "group_id": 48,
  "groups": [
    {
        "id": 2244,
        "course_id": 662,
        "degree_id": 1,
        "age_min": 1,
        "age_max": 99,
        "recommended_age": 1,
        "teachers_min": 1,
        "teachers_max": 1,
        "observations": "",
        "teacher_min_degree": 1,
        "auto": 0,
        "created_at": "2023-10-10 11:07:31",
        "updated_at": "2023-10-10 11:07:31",
        "league": "SKV",
        "annotation": "PT",
        "level": "Ptit Loup",
        "color": "#1C482C",
        "subgroups": [
            {
                "id": 3733,
                "course_group_id": 2244,
                "monitor_id": null,
                "max_participants": 3,
                "dates": [],
                "created_at": "2023-10-10 11:07:31",
                "updated_at": "2023-10-10 11:07:31",
                "monitor": {
                    "image": ""
                },
                "participants": 0,
                "total_max_participants": 3
            }
        ],
        "participants": 0,
        "total_max_participants": 3
    }
],
  "hour_max": null,
  "hour_min": null,
  "icon": "https://api.boukii.com/storage/icons/collectif_ski2x.png",
  "id": 662,
  "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAA",
  "libre": 0,
  "max_participants": 3,
  "name": "Fix Img test",
  "online": 1,
  "past_dates": 0,
  "price": 250,
  "price_ranges": [],
  "school_id": 1,
  "short_description": "<p>123</p>",
  "sport_id": 1,
  "station": {
      "id": 1,
      "name": "Les Paccots"
  },
  subtitle:"Collective Ski",
  total_dates: 1
}
