export const LEVELS = [
  {
      "annotation": "PT",
      "name": "Ptit Loup",
      "league": "SKV",
      "color": "#1C482C",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null

  },
  {
      "annotation": "JN",
      "name": "JN",
      "league": "SKV",
      "color": "#1C482C",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "DKV",
      "name": "Débutant Kid Village",
      "league": "SKV",
      "color": "#1C482C",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "PB",
      "name": "Prince / Pricesse Bleu",
      "league": "BLEU",
      "color": "#0E3991",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "RB",
      "name": "Roi / Reine Bleu",
      "league": "BLEU",
      "color": "#0E3991",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "SB",
      "name": "Star Bleu",
      "league": "BLEU",
      "color": "#0E3991",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "R1",
      "name": "R1",
      "league": "ROUGE",
      "color": "#572830",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "R2",
      "name": "R2",
      "league": "ROUGE",
      "color": "#572830",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "R3",
      "name": "R3",
      "league": "ROUGE",
      "color": "#572830",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "PN",
      "name": "Prince / Pricesse Noir",
      "league": "NOIR",
      "color": "#000000",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "ACA",
      "name": "Race",
      "league": "Academy",
      "color": "#7d7c7c",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "ACA",
      "name": "Freestyle",
      "league": "Academy",
      "color": "#7d7c7c",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  },
  {
      "annotation": "ACA",
      "name": "Freeride",
      "league": "Academy",
      "color": "#7d7c7c",
      "active": false,
      "sport_id": null,
      "school_id": null,
      "degree_order": null,
      "level": null,
      "progress": null
  }
];
